/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-secondary-fixed": "#1b1b1c",
              "on-tertiary-fixed": "#380d00",
              "on-surface": "#dce5d8",
              "surface-bright": "#333b33",
              "tertiary-fixed": "#ffdbcf",
              "on-tertiary-container": "#78351b",
              "error": "#ffb4ab",
              "tertiary-fixed-dim": "#ffb59b",
              "surface": "#0d150e",
              "on-primary-fixed": "#002109",
              "surface-container-high": "#242c24",
              "primary": "#4ff07f",
              "on-tertiary-fixed-variant": "#763319",
              "on-tertiary": "#581d05",
              "primary-container": "#25d366",
              "on-error": "#690005",
              "inverse-surface": "#dce5d8",
              "on-secondary": "#303030",
              "secondary": "#c8c6c5",
              "surface-container-lowest": "#081009",
              "surface-tint": "#3de273",
              "secondary-fixed": "#e5e2e1",
              "surface-container-low": "#151e16",
              "error-container": "#93000a",
              "on-surface-variant": "#bbcbb9",
              "primary-fixed": "#66ff8e",
              "tertiary": "#ffc7b4",
              "secondary-container": "#474746",
              "on-secondary-container": "#b7b5b4",
              "background": "#0d150e",
              "on-secondary-fixed-variant": "#474746",
              "surface-variant": "#2e372e",
              "on-primary-fixed-variant": "#005322",
              "primary-fixed-dim": "#3de273",
              "on-error-container": "#ffdad6",
              "inverse-on-surface": "#2a332a",
              "surface-container": "#19221a",
              "inverse-primary": "#006d2f",
              "tertiary-container": "#ffa07e",
              "outline": "#869584",
              "on-background": "#dce5d8",
              "secondary-fixed-dim": "#c8c6c5",
              "outline-variant": "#3c4a3d",
              "on-primary-container": "#005523",
              "surface-container-highest": "#2e372e",
              "surface-dim": "#0d150e",
              "on-primary": "#003915"
      },
      "borderRadius": {
              "DEFAULT": "1rem",
              "lg": "2rem",
              "xl": "3rem",
              "full": "9999px"
      },
      "spacing": {
              "gutter": "1.5rem",
              "stack-lg": "3rem",
              "stack-md": "1.5rem",
              "stack-sm": "0.5rem",
              "margin-mobile": "1rem",
              "container-max": "1280px"
      },
      "fontFamily": {
              "headline-xl": ["Inter"],
              "headline-md": ["Inter"],
              "body-md": ["Inter"],
              "headline-lg-mobile": ["Inter"],
              "body-lg": ["Inter"],
              "label-md": ["Inter"],
              "headline-lg": ["Inter"],
              "display-md": ["Inter"]
      },
      "fontSize": {
              "headline-xl": ["48px", { "lineHeight": "1.2", "fontWeight": "700" }],
              "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
              "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
              "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "700" }],
              "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
              "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500" }],
              "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
              "display-md": ["36px", { "lineHeight": "1.2", "fontWeight": "700" }]
      }
    },
  },
  plugins: [require('@tailwindcss/container-queries')],
}
